name: Terraform deploy

on:
    push:
        branches:
            - main
    workflow_dispatch:


permissions:
    id-token: write
    contents: read

env:
     TERRAFORM_WORKING_DIR: 'az-tf-repo/az-terraform/terraform-code/'
jobs:
      terraform-deploy-job:
        name: terraform deployment
        runs-on: 'ubuntu-latest'
        steps:
            - name: 'Checkout code'
              uses: actions/checkout@v5
              with:
                     fetch-depth: 0

            - name: 'Listing of the files'
              run:  |
                     ls -al $GITHUB_WORKSPACE
                    
            - name: 'Azure Authentication'
              uses: azure/login@v1
              with:
                     client-id: ${{ secrets.CLIENT_ID }}
                     tenant-id: ${{ secrets.TENANT_ID }}
                     enable-AzPSSession: true
                     allow-no-subscriptions: true
            - name: 'Setup Terraform'
              uses: hashicorp/setup-terraform@v2

            - name: 'Terraform init'
              run:  |
                     terraform init
              working-directory: ./terraform-code
                
            - name: 'Terraform plan'
              run:  |
                    terraform plan
              working-directory: ./terraform-code

            - name: 'Terraform apply'
              if: ${{ github.ref == 'refs/heads/main' && github.event_name == 'push'}}
              run:  |
                    terraform apply -auto-approve
              working-directory: ./terraform-code
              
                     
